version: "3.2"
services:
  web:
    build:
      context: ./php/
    container_name: sequdas_web
    restart: always
    networks:
      - frontend
      - backend
    depends_on:
      - mysql
    volumes:
      - ./sequdas/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
  mysql:
    image: mysql:5.7
    container_name: mysql-sequdas
    restart: always
    ports:
      - "31111:3306"
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=sequdas
      - MYSQL_USER=sequdas
      - MYSQL_PASSWORD=password
    volumes:
      - ./sequdas_db.sql:/docker-entrypoint-initdb.d/sequdas_db.sql
      - ./db:/var/lib/mysql
networks:
  frontend:
  backend: